### ISSUE TITLE
TypeError: {(intermediate value)(intermediate value)(intermediate value)}[packageManager] is not a function

### ISSUE THREAD

**Issue by bradzickafoose** [remix-run/blues-stack#116]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Run `npx create-remix --template remix-run/blues-stack`

### Expected Behavior

Installation to successfully complete.

### Actual Behavior

remix.init script fails with `TypeError: {(intermediate value)(intermediate value)(intermediate value)}[packageManager] is not a function`.

`npx create-remix --template remix-run/blues-stack`
? Where would you like to create your app? blues-stack
? Do you want me to run `npm install`? Yes
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

added 1333 packages, and audited 1334 packages in 28s

234 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 Running remix.init script
🚨 Oops, remix.init failed
```
TypeError: {(intermediate value)(intermediate value)(intermediate value)}[packageManager] is not a function
    at getPackageManagerCommand (/Users/home/Dev/blues-stack/remix.init/index.js:76:20)
    at main (/Users/home/Dev/blues-stack/remix.init/index.js:127:14)
    at init (/Users/home/.npm/_npx/82f938b29eb562d9/node_modules/@remix-run/dev/cli/commands.js:112:13)
    at async Object.create (/Users/home/.npm/_npx/82f938b29eb562d9/node_modules/@remix-run/dev/cli/commands.js:82:7)
    at async Object.run (/Users/home/.npm/_npx/82f938b29eb562d9/node_modules/@remix-run/dev/cli/run.js:330:9)
```

**Comment by MichaelDeBoey** [comment]
I just tried with `create-remix@latest` and this works for me.
Please make sure you use latest `create-remix` version as well.

**Comment by bradzickafoose** [comment]
Nice. 

`npx create-remix@latest --template remix-run/blues-stack` worked for me.

Thanks for the tip!
