### ISSUE TITLE
Blues Stack javascript version has errors upon build

### ISSUE THREAD

**Issue by nlewis84** [remix-run/blues-stack#127]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

`npx create-remix@latest **app-name**`
A pre-configured stack ready for production
Blues
JavaScript
`cd ./app-name`
`npm run docker`
`npm run setup` <-- First error 
`npm run build` <-- Second & Third errors

### Expected Behavior

You can follow the instructions and are able to start up the template without errors.

## First error

`npm run setup` <-- First error 
```
An error occured while running the seed command:
Error: Command failed with exit code 1: node --require tsconfig-paths/register prisma/seed.js
```

## Solution

Change
#### **`./prisma/seed.js`**
``` js
const bcrypt = require("bcryptjs").default;
```
to
```js
const bcrypt = require("bcryptjs");
```

Should clear the error and give you `The seed command has been executed.`

## Second error

`npm run build` <-- Second error
```
> build:server
> esbuild --platform=node --format=cjs ./server.ts --outdir=build --bundle

✘ [ERROR] Could not resolve "./server.ts"

1 error
ERROR: "build:server" exited with 1.
```

## Solution

Change
#### **`package.json`**
``` json
    "build:server": "esbuild --platform=node --format=cjs ./server.ts --outdir=build --bundle",
```
to
```json
    "build:server": "esbuild --platform=node --format=cjs ./server.js --outdir=build --bundle",
```

Now, run `npm run build` again.
Should clear the error and build the server.
Then, run `npm run dev`

## Third Error

```
> generate:css
> tailwindcss -o ./app/styles/tailwind.css "--watch"


/Users/nlewis/Development/apollos-axl/build/server.js:41653
var app = express();
          ^
TypeError: express is not a function
    at Object.<anonymous> (/Users/nlewis/Development/apollos-axl/build/server.js:41653:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
ERROR: "dev:server" exited with 1.
```

## Solution

Change
#### **`server.js`**
``` js
const path = require("path").default;
const express = require("express").default;
const compression = require("compression").default;
const morgan = require("morgan").default;

const { createRequestHandler } = require("@remix-run/express");
```
to
```js
import path from "path";
import express from "express";
import compression from "compression";
import morgan from "morgan";
import { createRequestHandler } from "@remix-run/express";
```

`npm run build`
`npm run dev`

:sparkles: No errors ✨
I'm happy to open a PR if this seems appropriate.

**Comment by pcattori** [comment]
Fixed by remix-run/remix#5163 .

For more detail on the approach taken, see the [decision doc for JS conversion support](decision doc: https://github.com/remix-run/remix/blob/dev/decisions/0008-only-support-js-conversion-for-app-code.md)
