### ISSUE TITLE
Remix blues stack problem when npm run docker

### ISSUE THREAD

**Issue by natehardy** [remix-run/blues-stack#129]
### What version of Remix are you using?

1.7.3

### Steps to Reproduce

1. follow startup instructions and install blues stack
2. npm run docker

### Expected Behavior

should start docker

### Actual Behavior

sh: docker-compose: command not found

**Comment by mcansh** [comment]
have you installed [Docker](https://www.docker.com/get-started)? just realizing we don't actually say you need to install it

**Comment by tsnieman** [comment]
This is likely an issue of this repo referencing `docker-compose` (which is the "old" version) versus `docker compose` (the new version).

Changing the `package.json` script to use `docker compose` (no dash) should make the script work, assuming that you installed Docker recently and have the new version of `docker compose` installed.

Reference:
https://docs.docker.com/compose/compose-v2/

**Comment by jamestrenda** [comment]
> have you installed [Docker](https://www.docker.com/get-started)? just realizing we don't actually say you need to install it

They still don't say it, and if I hadn't used Docker Desktop before on my other computer, I wouldn't have known what to do. VS Code did prompt me to install it, but I was way ahead of it.

**Comment by JuanVMaya** [comment]
Hi there, if I were to open a PR fix for this, is there a contribution guide to do so?
