### ISSUE TITLE
Gitpod link broken

### ISSUE THREAD

**Issue by goldylucks** [remix-run/blues-stack#134]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

open README and click the gitpod button, goes to https://gitpod.io/from-referrer, and after auth it says this:

![image](https://user-images.githubusercontent.com/6963212/200815095-da7644a7-5d6d-45ea-a532-bd2e13dd6cdc.png)

### Expected Behavior

I'm unfamiliar with gitpod TBH, tho I don't know what should happen :)

### Actual Behavior

See steps to repdoruce

**Comment by mcansh** [comment]
strange, i swear it used to work - looks like the URL should be `https://gitpod.io/#https://github.com/remix-run/blues-stack/tree/main`

**Comment by goldylucks** [comment]
haha no need to swear man, I believe you :)
