### ISSUE TITLE
Hydration error: Initial UI does not match server

### ISSUE THREAD

**Issue by collinglass** [remix-run/blues-stack#150]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. From the readme
2. Click the gitpod button
3. run the server
4. go to localhost:3000
5. open console

### Expected Behavior

I have made no modifications so should work smoothly with no errors.

### Actual Behavior

![image](https://user-images.githubusercontent.com/3614712/213668780-16a20a2b-a0e5-4cdd-9a5c-595f1cf304b3.png)

**Comment by collinglass** [comment]
As a follow up, I also tried a fresh install using `npx create-remix@latest --template remix-run/blues-stack` and same issue.

**Comment by siddharthborderwala** [comment]
Have you found any fixes for this issue? @collinglass

**Comment by MichaelDeBoey** [comment]
This is probably because a browser extension is injecting code

You can read more about it in the gotchas: https://remix.run/docs/en/main/pages/gotchas#md-browser-extensions-injecting-code
