### ISSUE TITLE
Race condition in npm run dev 

### ISSUE THREAD

**Issue by humphd** [remix-run/blues-stack#159]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

```
npm run dev
```

### Expected Behavior

I would expect `npm run dev` to always build and start the various servers without problems related to build timing/order.

### Actual Behavior

Sometimes when running `npm run dev`, the various parallel build processes happen in an order such that the server can't start:

https://github.com/remix-run/blues-stack/blob/main/package.json#L10-L14

The only way to fix this is to manually run `npm run build` then re-try `npm run dev`.  I guess because these commands aren't finishing (due to `--watch`), it isn't easy to know when to run the next step?  Regardless, it would be good to find a better way to do this that doesn't randomly fail.

**Comment by humphd** [comment]
I found that even changing https://github.com/remix-run/blues-stack/blob/main/package.json#L10 to this helps a bunch:

```json
"dev": "run-p dev:build dev:remix dev:server",
```

**Comment by kwabe007** [comment]
Just ran into this issue today as well when trying to follow this stack's dev/build scripts. Explicitly expanding the script names didn't work for me but as a workaround I've set a three second delay for the `dev:server` script:
```json
"delay": "node -e \"setTimeout(() => process.exit(0), 3000)\"",
"dev:server": "npm run delay && cross-env NODE_ENV=development node --inspect --require ./node_modules/dotenv/config --require ./mocks ./build/server.js"
```
And now it works without having to run `npm run build` first.

**Comment by humphd** [comment]
@kwabe007 this is better for sure, thanks for sharing.

**Comment by jsrhodes15** [comment]
I'm wondering if this issue should be resolved with the latest release of `remix`? 

https://github.com/remix-run/remix/releases/tag/remix%401.16.0

I have used the Blue Stack pretty much as-is, so I'm not 100% sure on the internals. But if I understand correctly, couldn't the scripts be changed such that `dev` is just a single command?

**Comment by Jesus-fhz** [comment]
Hi there,

Updating to `node 20` fixed this issue for me.
