### ISSUE TITLE
blues-stack 2.0.0-pre.5 - LiveReload is not working

### ISSUE THREAD

**Issue by codelover2k** [remix-run/blues-stack#203]
### Have you experienced this bug with the latest version of the template?

no

### Steps to Reproduce

```
npx create-remix@pre --template remix-run/blues-stack
cd my-remix-app
npx upgrade-remix pre
npm run build
npm run dev
```

### Expected Behavior

working LiveReload

### Actual Behavior

LiveReload is not working so I checked the console and I get this error:
```
ndex):37 WebSocket connection to 'ws://localhost:8002/socket' failed: 
remixLiveReloadConnect @ (index):37
(index):106 Remix dev asset server web socket error:
```
Thenn in the `app/root.tsx` I changed this:
```jsx
<LiveReload />
// to this
<LiveReload port={8002} />
```
Now I am getting this error:
```
Ucaught TypeError: Failed to construct 'URL': Invalid URL
    at remixLiveReloadConnect ((index):34:40)
    at (index):110:17
remixLiveReloadConnect @ (index):34
(anonymous) @ (index):110
```
and LiveReload is still not working.

**Comment by codelover2k** [comment]
Tested `blues-stack 2.0.0-pre.4`
There LiveReload is working with no problems

**Comment by pcattori** [comment]
Cannot reproduce on `2.0.0-pre.6`
