### ISSUE TITLE
User `postgres` was denied access on the database `postgres.public`

### ISSUE THREAD

**Issue by tconroy** [remix-run/blues-stack#49]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Following the setup instructions in the readme:
* `npm run docker`
* wait for docker container to finish setting up
* `npm run setup`

### Expected Behavior

`npm run setup` completes successfully

### Actual Behavior

`npm run setup` fails with the following error

```
Error: P1010: User `postgres` was denied access on the database `postgres.public`
```

Full terminal output:
```
~/Desktop/demoapp
❯ npm run docker

> docker
> docker-compose up -d

Creating network "demoapp_default" with the default driver
Creating demoapp_postgres_1 ... done

~/Desktop/demoapp
❯ npm run setup

> setup
> prisma migrate dev && prisma db seed

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5432"

Error: P1010: User `postgres` was denied access on the database `postgres.public`
```

**Comment by tconroy** [comment]
This is on an M1 MacBook Pro, running Docker Desktop 4.6.1 (76265).  Otherwise just followed exact setup in the README.

**Comment by tconroy** [comment]
I found that modifying my `.env` `DATABASE_URL` to specify my user account name (instead of `postgres`), seems to fix this:

```diff
- DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
+ DATABASE_URL="postgresql://tom:postgres@localhost:5432/postgres"
```

But not entirely sure why? Would be nice is `postgres` worked so any developer on my team could get up and running quickly.

**Comment by bradymwilliams** [comment]
Same issue. Same versions. Updating to user name in env DATABASE_URL also worked for me.

**Comment by CanRau** [comment]
Same error here, just bootstrapped a new blues stack. strangely the one I bootstrapped couple of days ago (pretty sure less than 19 days) didn't fail 🤔

**Comment by Saad29** [comment]
> I found that modifying my `.env` `DATABASE_URL` to specify my user account name (instead of `postgres`), seems to fix this:
> 
> ```diff
> - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
> + DATABASE_URL="postgresql://tom:postgres@localhost:5432/postgres"
> ```
> 
> But not entirely sure why? Would be nice is `postgres` worked so any developer on my team could get up and running quickly.

Same problem here. By the way, which user name do you mean?

**Comment by tconroy** [comment]
> Same problem here. By the way, which user name do you mean?

@Saad29: I mean the name of your user account. What you see when you run this in your shell:
```shell
echo $USER
```

**Comment by mcansh** [comment]
looking into this a bit, haven't found anything out of the ordinary in these set ups or during a bit of googling..

but in the interim, you should be able to do the following instead:

```diff
version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
-   environment:
-     - POSTGRES_USER=postgres
-     - POSTGRES_PASSWORD=postgres
-     - POSTGRES_DB=postgres
+   env_file:
+   	— .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

```

then add the following to a .env file

```
POSTGRES_USER=myuser
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
```

you might also be able to keep the password/db in the compose env, but im not sure if those are a one or the other type of thing

**Comment by machour** [comment]
Closing this issue as no response was provided.
Feel free to re-open it if it's still a problem.

**Comment by sostenesapollo** [comment]
My issue is related to postgres in another server, when I try it it shows 
```
Error: Can't reach database server at `undefined.34.121.158.52`:`5432`
```
But just with this remix app, with nestjs and  using local db it works normally

**Comment by postmeback** [comment]
![Postgresql-Error](https://github.com/remix-run/blues-stack/assets/14862687/ac62c62b-deba-4b21-b3d6-182dfc22e279)


I have implemented all the above suggestions, but none helps. Also, I am pretty new to Postgres, so would be nice if any suggestion comes up.

Please reopen the issue

**Comment by lexNwimue** [comment]
@postmeback did you eventually find a fix? I'm in the same shoes now

**Comment by Benrobo** [comment]
> I had this problem and it was related to having postgres installed and running on my mac separately from the remix instance inside Docker.
> 
> Killing the local install solved it for me.

This works for me. I had a separate instance of posgres running aside from the one running in my docker container. stoping the local postgres instance made resolve the issue.

**Comment by soom-lupulus** [comment]
1. you should find out the file `pg_hba.conf`
2. add this line `host    all             postgres        172.16.0.0/12          md5 ` to configurate the connection address
3. if it doesn't work, try another address which suits your environment
