### ISSUE TITLE
`npm run dev` has to be restarted after Prisma change.

### ISSUE THREAD

**Issue by kluplau** [remix-run/blues-stack#52]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Init Blues template
2. Add `author String` to `schema.prisma`
3. Update `note.server.ts` with author key.
4. Add `<p className="py-6">{data.note.author}</p>` to `$noteId.tsx`
5. In `new.tsx` copy functionality from `title` and name it `author`.
6. Run migration `npx prisma migrate dev --name adding-author`
7. Navigate to `http://localhost:3000/notes/new` and try to create a new note

### Expected Behavior

New note will be displayed after submit.

### Actual Behavior

Error is shown. You have to rerun `npm run dev` to get it working again.

**Comment by mcansh** [comment]
this is due to `prisma generate` making changes to `node_modules`, you could add a check for `node_modules/@prisma/client` to the `purgeRequireCache` function
