### ISSUE TITLE
hot reload doesn't work

### ISSUE THREAD

**Issue by thatvegandev** [remix-run/blues-stack#79]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

`npx create-remix@latest` with blues stack (I chose typescript)

no customizations, just hot reload doesn't work. I can see things rebuild but no updates in the browser.

### Expected Behavior

The app rebuilds and the appropriate updates are displayed in the browser.

### Actual Behavior

The app rebuilds but no changes in the browser

**Comment by braginteractive** [comment]
Same issue.

**Comment by mcansh** [comment]
this is an upstream issue that we're fixing in Remix - can you try passing the port explicitly with `<LiveReload port={Number(process.env.REMIX_DEV_SERVER_WS_PORT)} />`?

**Comment by rndomz** [comment]
Thank you @mcansh, I was able to make it work.

**Comment by machour** [comment]
Closing this issue, it will be fixed in remix.
