### ISSUE TITLE
Error connect database

### ISSUE THREAD

**Issue by zevsdflkjiuxcvb** [remix-run/blues-stack#88]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Run `npx create-remix --template remix-run/blues-stack` in console
then `npm run dev`, I get this error
Here is my db URL in .env file: `DATABASE_URL="postgresql://postgres:norqgrhigqygxsywkasp@db.norqgrhigqygxsywkasp.supabase.co:5432/postgres"`
```
app ready: http://localhost:3000
(node:9388) UnhandledPromiseRejectionWarning: Error: Can't reach database server at `undefined.db.norqgrhigqygxsywkasp.supabase.co`:`5432`

Please make sure your database server is running at `undefined.db.norqgrhigqygxsywkasp.supabase.co`:`5432`.
    at D:\job\test\remix-blue\node_modules\@prisma\client\runtime\index.js:44801:20
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior

Just hope plug and run :(

### Actual Behavior

![image](https://user-images.githubusercontent.com/86824564/175238983-b2bcd523-8a28-4bc5-aa22-4b238fa4b367.png)

**Comment by mcansh** [comment]
did you opt out of installing dependencies during "create-remix"? if not, a .env should have been generated for you during "remix init" https://github.com/remix-run/blues-stack/blob/main/remix.init/index.js#L63

if you do opt out, you should be seeing the following which prompts you to install your dependencies and run "npx remix init" ![](https://user-images.githubusercontent.com/11698668/173191363-76d9bc06-12c2-4ea1-b2ff-a10c9e726e94.png)

**Comment by mcansh** [comment]
ah actually, re-read your issue, looks like the DB url the app has isn't correct (see `undefined`

**Comment by zevsdflkjiuxcvb** [comment]
> undefined

Yeah I know, but why? I should be ran, right ?

**Comment by mcansh** [comment]
what's weird is there is no subdomain before `.db.nor...` so im not sure where the undefined is even coming from

**Comment by juanmcampos** [comment]
> 

It seem to come from db.server.ts file there is a conditional   if (!isLocalHost) { } which sets the databaseurl for FLY_REGION which if you are not using and you are not localhost then it's breaks.

**Comment by juanmcampos** [comment]
I made a PR with a quick fix :P maybe not the best solution but hope it helps https://github.com/remix-run/blues-stack/pull/101

**Comment by phifa** [comment]
I just ran into the same issue. It's not fixed, is it?

**Comment by tylerdukedev** [comment]
Anyone find a solution for this? I'm running in to the same issue. I've altered my db.server file to something more generic: 

`import { PrismaClient } from "@prisma/client";

let db: PrismaClient;

declare global {
  var db: PrismaClient | undefined;
}

// PrismaClient is attached to the `global` object in development to prevent
// exhausting your database connection limit.
if (process.env.NODE_ENV === "production") {
  db = new PrismaClient();
  db.$connect();
} else {
  if (!global.db) {
    global.db = new PrismaClient();
    global.db.$connect();
  }

  db = global.db;
}

export default db;
`

Still doesn't work.

**Comment by machour** [comment]
Fixed by https://github.com/remix-run/blues-stack/commit/c8f2dec9a6e5c697e2cbfb01e76245112702d313
