### ISSUE TITLE
Latest commit breaks setup because no db is running

### ISSUE THREAD

**Issue by zachrip** [remix-run/blues-stack#96]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Use the blues stack to create a project and it eventually runs `execSync("npm run setup", { stdio: "inherit", cwd: rootDirectory });` which tries to connect to a running database - if you're using this stack it's unlikely there will already be a postgres instance running so it fails and breaks the setup.

### Expected Behavior

I would either expect it to try and run `npm run docker` or pass this process onto the user.

### Actual Behavior

It runs `npm run setup` without first making sure a db is running.

**Comment by kentcdodds** [comment]
That was definitely a copy/paste error. Thank you!
